### ISSUE TITLE
Ryujinx AutoUpdate  Windows certificate store Error

### ISSUE THREAD

**Issue by ghost** [Dudejoe870/RyujinxAutoUpdate#1]
Severity Code Description Project Classification Path File Line Suppression State
Warning The code signing certificate could not be found in the current user's Windows certificate store. To correct this, disable the ClickOnce manifest signature, or install the certificate in the certificate store. RyujinxAutoUpdate 1

**Comment by Dudejoe870** [comment]
This should be fixed now.
